apiVersion: 1

datasources:
  - name: MariaDB
    type: mysql
    url: 127.0.0.1:3307
    user: mariadbuser
    database: monitoring
    jsonData:
      maxOpenConns: 10
    secureJsonData:
      password: Samikshya@123
